[Acl]
homepage = "https://savannah.nongnu.org/projects/acl"
url = "https://download.savannah.gnu.org/releases/acl/acl-2.3.2.tar.xz"
md5 = "590765dee95907dbc3c856f7255bd669"

[Attr]
homepage = "https://savannah.nongnu.org/projects/attr"
url = "https://download.savannah.gnu.org/releases/attr/attr-2.5.2.tar.gz"
md5 = "227043ec2f6ca03c0948df5517f9c927"

[Autoconf]
homepage = "https://www.gnu.org/software/autoconf/"
url = "https://ftp.gnu.org/gnu/autoconf/autoconf-2.72.tar.xz"
md5 = "1be79f7106ab6767f18391c5e22be701"

[Automake]
homepage = "https://www.gnu.org/software/automake/"
url = "https://ftp.gnu.org/gnu/automake/automake-1.16.5.tar.xz"
md5 = "4017e96f89fca45ca946f1c5db6be714"

[Bash]
homepage = "https://www.gnu.org/software/bash/"
url = "https://ftp.gnu.org/gnu/bash/bash-5.2.21.tar.gz"
md5 = "ad5b38410e3bf0e9bcc20e2765f5e3f9"

[Bc]
homepage = "https://git.gavinhoward.com/gavin/bc"
url = "https://github.com/gavinhoward/bc/releases/download/6.7.5/bc-6.7.5.tar.xz"
md5 = "e249b1f86f886d6fb71c15f72b65dd3d"

[Binutils]
homepage = "https://www.gnu.org/software/binutils/"
url = "https://sourceware.org/pub/binutils/releases/binutils-2.42.tar.xz"
md5 = "a075178a9646551379bfb64040487715"

[Bison]
homepage = "https://www.gnu.org/software/bison/"
url = "https://ftp.gnu.org/gnu/bison/bison-3.8.2.tar.xz"
md5 = "c28f119f405a2304ff0a7ccdcc629713"

[Bzip2]
homepage = ""
url = "https://www.sourceware.org/pub/bzip2/bzip2-1.0.8.tar.gz"
md5 = "67e051268d0c475ea773822f7500d0e5"

[Check]
homepage = "https://libcheck.github.io/check"
url = "https://github.com/libcheck/check/releases/download/0.15.2/check-0.15.2.tar.gz"
md5 = "50fcafcecde5a380415b12e9c574e0b2"

[Coreutils]
homepage = "https://www.gnu.org/software/coreutils/"
url = "https://ftp.gnu.org/gnu/coreutils/coreutils-9.4.tar.xz"
md5 = "459e9546074db2834eefe5421f250025"

[DejaGNU]
homepage = "https://www.gnu.org/software/dejagnu/"
url = "https://ftp.gnu.org/gnu/dejagnu/dejagnu-1.6.3.tar.gz"
md5 = "68c5208c58236eba447d7d6d1326b821"

[Diffutils]
homepage = "https://www.gnu.org/software/diffutils/"
url = "https://ftp.gnu.org/gnu/diffutils/diffutils-3.10.tar.xz"
md5 = "2745c50f6f4e395e7b7d52f902d075bf"

[E2fsprogs]
homepage = "http://e2fsprogs.sourceforge.net/"
url = "https://downloads.sourceforge.net/project/e2fsprogs/e2fsprogs/v1.47.0/e2fsprogs-1.47.0.tar.gz"
md5 = "6b4f18a33873623041857b4963641ee9"

[Elfutils]
homepage = "https://sourceware.org/elfutils/"
url = "https://sourceware.org/ftp/elfutils/0.190/elfutils-0.190.tar.bz2"
md5 = "79ad698e61a052bea79e77df6a08bc4b"

# Update for fix https://www.linuxfromscratch.org/blfs/advisories/consolidated.html#sa-12.1-010
[Expat]
homepage = "https://libexpat.github.io/"
url = "https://github.com/libexpat/libexpat/releases/download/R_2_6_2/expat-2.6.2.tar.xz"
md5 = "0cb75c8feb842c0794ba89666b762a2d"

[Expect]
homepage = "https://core.tcl.tk/expect/"
url = "https://prdownloads.sourceforge.net/expect/expect5.45.4.tar.gz"
md5 = "00fce8de158422f5ccd2666512329bd2"

[File]
homepage = "https://www.darwinsys.com/file/"
url = "https://astron.com/pub/file/file-5.45.tar.gz"
md5 = "26b2a96d4e3a8938827a1e572afd527a"

[Findutils]
homepage = "https://www.gnu.org/software/findutils/"
url = "https://ftp.gnu.org/gnu/findutils/findutils-4.9.0.tar.xz"
md5 = "4a4a547e888a944b2f3af31d789a1137"

[Flex]
homepage = "https://github.com/westes/flex"
url = "https://github.com/westes/flex/releases/download/v2.6.4/flex-2.6.4.tar.gz"
md5 = "2882e3179748cc9f9c23ec593d6adc8d"

[Flit-core]
homepage = "https://pypi.org/project/flit-core/"
url = "https://pypi.org/packages/source/f/flit-core/flit_core-3.9.0.tar.gz"
md5 = "3bc52f1952b9a78361114147da63c35b"

[Gawk]
homepage = "https://www.gnu.org/software/gawk/"
url = "https://ftp.gnu.org/gnu/gawk/gawk-5.3.0.tar.xz"
md5 = "97c5a7d83f91a7e1b2035ebbe6ac7abd"

[GCC]
homepage = "https://gcc.gnu.org/"
url = "https://ftp.gnu.org/gnu/gcc/gcc-13.2.0/gcc-13.2.0.tar.xz"
md5 = "e0e48554cc6e4f261d55ddee9ab69075"

[GDBM]
homepage = "https://www.gnu.org/software/gdbm/"
url = "https://ftp.gnu.org/gnu/gdbm/gdbm-1.23.tar.gz"
md5 = "8551961e36bf8c70b7500d255d3658ec"

[Gettext]
homepage = "https://www.gnu.org/software/gettext/"
url = "https://ftp.gnu.org/gnu/gettext/gettext-0.22.4.tar.xz"
md5 = "2d8507d003ef3ddd1c172707ffa97ed8"

[Glibc]
homepage = "https://www.gnu.org/software/libc/"
url = "https://ftp.gnu.org/gnu/glibc/glibc-2.39.tar.xz"
md5 = "be81e87f72b5ea2c0ffe2bedfeb680c6"

[GMP]
homepage = "https://www.gnu.org/software/gmp/"
url = "https://ftp.gnu.org/gnu/gmp/gmp-6.3.0.tar.xz"
md5 = "956dc04e864001a9c22429f761f2c283"

[Gperf]
homepage = "https://www.gnu.org/software/gperf/"
url = "https://ftp.gnu.org/gnu/gperf/gperf-3.1.tar.gz"
md5 = "9e251c0a618ad0824b51117d5d9db87e"

[Grep]
homepage = "https://www.gnu.org/software/grep/"
url = "https://ftp.gnu.org/gnu/grep/grep-3.11.tar.xz"
md5 = "7c9bbd74492131245f7cdb291fa142c0"

[Groff]
homepage = "https://www.gnu.org/software/groff/"
url = "https://ftp.gnu.org/gnu/groff/groff-1.23.0.tar.gz"
md5 = "5e4f40315a22bb8a158748e7d5094c7d"

[GRUB]
homepage="https://www.gnu.org/software/grub/"
url = "https://ftp.gnu.org/gnu/grub/grub-2.12.tar.xz"
md5 = "60c564b1bdc39d8e43b3aab4bc0fb140"

[Gzip]
homepage = "https://www.gnu.org/software/gzip/"
url = "https://ftp.gnu.org/gnu/gzip/gzip-1.13.tar.xz"
md5 = "d5c9fc9441288817a4a0be2da0249e29"

[Iana-Etc]
homepage = "https://www.iana.org/protocols"
url = "https://github.com/Mic92/iana-etc/releases/download/20240125/iana-etc-20240125.tar.gz"
md5 = "aed66d04de615d76c70890233081e584"

[Inetutils]
homepage = "https://www.gnu.org/software/inetutils/"
url = "https://ftp.gnu.org/gnu/inetutils/inetutils-2.5.tar.xz"
md5 = "9e5a6dfd2d794dc056a770e8ad4a9263"

[Intltool]
homepage = "https://freedesktop.org/wiki/Software/intltool"
url = "https://launchpad.net/intltool/trunk/0.51.0/+download/intltool-0.51.0.tar.gz"
md5 = "12e517cac2b57a0121cda351570f1e63"

[IPRoute2]
homepage = "https://www.kernel.org/pub/linux/utils/net/iproute2/"
url = "https://www.kernel.org/pub/linux/utils/net/iproute2/iproute2-6.7.0.tar.xz"
md5 = "35d8277d1469596b7edc07a51470a033"

[Jinja2]
homepage = "https://jinja.palletsprojects.com/en/3.1.x/"
url = "https://pypi.org/packages/source/J/Jinja2/Jinja2-3.1.3.tar.gz"
md5 = "caf5418c851eac59e70a78d9730d4cea"

[Kbd]
homepage = "https://kbd-project.org/"
url = "https://www.kernel.org/pub/linux/utils/kbd/kbd-2.6.4.tar.xz"
md5 = "e2fd7adccf6b1e98eb1ae8d5a1ce5762"

[Kmod]
homepage = "https://github.com/kmod-project/kmod"
url = "https://www.kernel.org/pub/linux/utils/kernel/kmod/kmod-31.tar.xz"
md5 = "6165867e1836d51795a11ea4762ff66a"

[Less]
homepage = "https://www.greenwoodsoftware.com/less/"
url = "https://www.greenwoodsoftware.com/less/less-643.tar.gz"
md5 = "cf05e2546a3729492b944b4874dd43dd"

[LFS-Bootscripts]
homepage = ""
url = "https://www.linuxfromscratch.org/lfs/downloads/12.1/lfs-bootscripts-20230728.tar.xz"
md5 = "a236eaa9a1f699bc3fb6ab2acd7e7b6c"

[Libcap]
homepage = "https://sites.google.com/site/fullycapable/"
url = "https://www.kernel.org/pub/linux/libs/security/linux-privs/libcap2/libcap-2.69.tar.xz"
md5 = "4667bacb837f9ac4adb4a1a0266f4b65"

[Libffi]
homepage = "https://sourceware.org/libffi/"
url = "https://github.com/libffi/libffi/releases/download/v3.4.4/libffi-3.4.4.tar.gz"
md5 = "0da1a5ed7786ac12dcbaf0d499d8a049"

[Libpipeline]
homepage = "https://libpipeline.nongnu.org/"
url = "https://download.savannah.gnu.org/releases/libpipeline/libpipeline-1.5.7.tar.gz"
md5 = "1a48b5771b9f6c790fb4efdb1ac71342"

[Libtool]
homepage = "https://www.gnu.org/software/libtool/"
url = "https://ftp.gnu.org/gnu/libtool/libtool-2.4.7.tar.xz"
md5 = "2fc0b6ddcd66a89ed6e45db28fa44232"

[Libxcrypt]
homepage = "https://github.com/besser82/libxcrypt/"
url = "https://github.com/besser82/libxcrypt/releases/download/v4.4.36/libxcrypt-4.4.36.tar.xz"
md5 = "b84cd4104e08c975063ec6c4d0372446"

# Use the latest stable version of Linux (20240602)
[Linux]
homepage = "https://www.kernel.org/"
url = "https://www.kernel.org/pub/linux/kernel/v6.x/linux-6.9.3.tar.xz"
md5 = "1cedde7aa0f267c61897cead90a74788"

[M4]
homepage = "https://www.gnu.org/software/m4/"
url = "https://ftp.gnu.org/gnu/m4/m4-1.4.19.tar.xz"
md5 = "0d90823e1426f1da2fd872df0311298d"

[Make]
homepage = "https://www.gnu.org/software/make/"
url = "https://ftp.gnu.org/gnu/make/make-4.4.1.tar.gz"
md5 = "c8469a3713cbbe04d955d4ae4be23eeb"

[Man-DB]
homepage = "https://www.nongnu.org/man-db/"
url = "https://download.savannah.gnu.org/releases/man-db/man-db-2.12.0.tar.xz"
md5 = "67e0052fa200901b314fad7b68c9db27"

[Man-pages]
homepage = "https://www.kernel.org/doc/man-pages/"
url = "https://www.kernel.org/pub/linux/docs/man-pages/man-pages-6.06.tar.xz"
md5 = "26b39e38248144156d437e1e10cb20bf"

[MarkupSafe]
homepage = "https://palletsprojects.com/p/markupsafe/"
url = "https://pypi.org/packages/source/M/MarkupSafe/MarkupSafe-2.1.5.tar.gz"
md5 = "8fe7227653f2fb9b1ffe7f9f2058998a"

[Meson]
homepage = "https://mesonbuild.com"
url = "https://github.com/mesonbuild/meson/releases/download/1.3.2/meson-1.3.2.tar.gz"
md5 = "2d0ebd3a24249617b1c4d30026380cf8"

[MPC]
homepage = "https://www.multiprecision.org/"
url = "https://ftp.gnu.org/gnu/mpc/mpc-1.3.1.tar.gz"
md5 = "5c9bc658c9fd0f940e8e3e0f09530c62"

[MPFR]
homepage = "https://www.mpfr.org/"
url = "https://ftp.gnu.org/gnu/mpfr/mpfr-4.2.1.tar.xz"
md5 = "523c50c6318dde6f9dc523bc0244690a"

[Ncurses]
homepage = "https://www.gnu.org/software/ncurses/"
url = "https://anduin.linuxfromscratch.org/LFS/ncurses-6.4-20230520.tar.xz"
md5 = "c5367e829b6d9f3f97b280bb3e6bfbc3"

[Ninja]
homepage = "https://ninja-build.org/"
url = "https://github.com/ninja-build/ninja/archive/v1.11.1/ninja-1.11.1.tar.gz"
md5 = "32151c08211d7ca3c1d832064f6939b0"

[OpenSSL]
homepage = "https://www.openssl.org/"
url = "https://www.openssl.org/source/openssl-3.2.1.tar.gz"
md5 = "c239213887804ba00654884918b37441"

[Patch]
homepage = "https://savannah.gnu.org/projects/patch/"
url = "https://ftp.gnu.org/gnu/patch/patch-2.7.6.tar.xz"
md5 = "78ad9937e4caadcba1526ef1853730d5"

[Perl]
homepage = "https://www.perl.org/"
url = "https://www.cpan.org/src/5.0/perl-5.38.2.tar.xz"
md5 = "d3957d75042918a23ec0abac4a2b7e0a"

[Pkgconf]
homepage = "http://pkgconf.org/"
url = "https://distfiles.ariadne.space/pkgconf/pkgconf-2.1.1.tar.xz"
md5 = "bc29d74c2483197deb9f1f3b414b7918"

[Procps]
homepage = "https://gitlab.com/procps-ng/procps/"
url = "https://sourceforge.net/projects/procps-ng/files/Production/procps-ng-4.0.4.tar.xz"
md5 = "2f747fc7df8ccf402d03e375c565cf96"

[Psmisc]
homepage = "https://gitlab.com/psmisc/psmisc"
url = "https://sourceforge.net/projects/psmisc/files/psmisc/psmisc-23.6.tar.xz"
md5 = "ed3206da1184ce9e82d607dc56c52633"

[Python]
homepage = "https://www.python.org/"
url = "https://www.python.org/ftp/python/3.12.2/Python-3.12.2.tar.xz"
md5 = "e7c178b97bf8f7ccd677b94d614f7b3c"

[Python-Documentation]
homepage=""
url = "https://www.python.org/ftp/python/doc/3.12.2/python-3.12.2-docs-html.tar.bz2"
md5 = "8a6310f6288e7f60c3565277ec3b5279"

[Readline]
homepage = "https://tiswww.case.edu/php/chet/readline/rltop.html"
url = "https://ftp.gnu.org/gnu/readline/readline-8.2.tar.gz"
md5 = "4aa1b31be779e6b84f9a96cb66bc50f6"

[Sed]
homepage = "https://www.gnu.org/software/sed/"
url = "https://ftp.gnu.org/gnu/sed/sed-4.9.tar.xz"
md5 = "6aac9b2dbafcd5b7a67a8a9bcb8036c3"

[Setuptools]
homepage = "https://pypi.org/project/setuptools/"
url = "https://pypi.org/packages/source/s/setuptools/setuptools-69.1.0.tar.gz"
md5 = "6f6eb780ce12c90d81ce243747ed7ab0"

[Shadow]
homepage = "https://github.com/shadow-maint/shadow/"
url = "https://github.com/shadow-maint/shadow/releases/download/4.14.5/shadow-4.14.5.tar.xz"
md5 = "452b0e59f08bf618482228ba3732d0ae"

[Sysklogd]
homepage = "https://www.infodrom.org/projects/sysklogd/"
url = "https://www.infodrom.org/projects/sysklogd/download/sysklogd-1.5.1.tar.gz"
md5 = "c70599ab0d037fde724f7210c2c8d7f8"

[Systemd]
homepage = "https://www.freedesktop.org/wiki/Software/systemd/"
url = "https://github.com/systemd/systemd/archive/v255/systemd-255.tar.gz"
md5 = "521cda27409a9edf0370c128fae3e690"

[Systemd-Man-Pages]
homepage = "https://www.freedesktop.org/wiki/Software/systemd/"
url = "https://anduin.linuxfromscratch.org/LFS/systemd-man-pages-255.tar.xz"
md5 = "1ebe54d7a80f9abf8f2d14ddfeb2432d"

[Sysvinit]
homepage = "https://savannah.nongnu.org/projects/sysvinit"
url = "https://github.com/slicer69/sysvinit/releases/download/3.08/sysvinit-3.08.tar.xz"
md5 = "81a05f28d7b67533cfc778fcadea168c"

[Tar]
homepage = "https://www.gnu.org/software/tar/"
url = "https://ftp.gnu.org/gnu/tar/tar-1.35.tar.xz"
md5 = "a2d8042658cfd8ea939e6d911eaf4152"

[Tcl]
homepage = "http://tcl.sourceforge.net/"
url = "https://downloads.sourceforge.net/tcl/tcl8.6.13-src.tar.gz"
md5 = "0e4358aade2f5db8a8b6f2f6d9481ec2"

[Tcl-Documentation]
url = "https://downloads.sourceforge.net/tcl/tcl8.6.13-html.tar.gz"
md5 = "4452f2f6d557f5598cca17b786d6eb68"

[Texinfo]
homepage = "https://www.gnu.org/software/texinfo/"
url = "https://ftp.gnu.org/gnu/texinfo/texinfo-7.1.tar.xz"
md5 = "edd9928b4a3f82674bcc3551616eef3b"

[Time-Zone-Data]
homepage = "https://www.iana.org/time-zones"
url = "https://www.iana.org/time-zones/repository/releases/tzdata2024a.tar.gz"
md5 = "2349edd8335245525cc082f2755d5bf4"

[Udev-lfs]
homepage = ""
url = "https://anduin.linuxfromscratch.org/LFS/udev-lfs-20230818.tar.xz"
md5 = "acd4360d8a5c3ef320b9db88d275dae6"

[Util-linux]
homepage = "https://git.kernel.org/pub/scm/utils/util-linux/util-linux.git/"
url = "https://www.kernel.org/pub/linux/utils/util-linux/v2.39/util-linux-2.39.3.tar.xz"
md5 = "f3591e6970c017bb4bcd24ae762a98f5"

# Use the latest vim (20240602)
[Vim]
homepage = "https://www.vim.org"
url = "https://github.com/vim/vim/archive/v9.1.0457/vim-9.1.0457.tar.gz"
md5 = "563b43bb4b29f4e8f309802c39b88154"

[Wheel]
homepage = "https://pypi.org/project/wheel/"
url = "https://pypi.org/packages/source/w/wheel/wheel-0.42.0.tar.gz"
md5 = "802ad6e5f9336fcb1c76b7593f0cd22d"

[XML-Parser]
homepage = "https://github.com/chorny/XML-Parser"
url = "https://cpan.metacpan.org/authors/id/T/TO/TODDR/XML-Parser-2.47.tar.gz"
md5 = "89a8e82cfd2ad948b349c0a69c494463"

[Xz-Utils]
homepage = "https://tukaani.org/xz"
url = "https://github.com/tukaani-project/xz/releases/download/v5.4.6/xz-5.4.6.tar.xz"
md5 = "7ade7bd1181a731328f875bec62a9377"

[Zlib]
homepage = "https://zlib.net/"
url = "https://zlib.net/fossils/zlib-1.3.1.tar.gz"
md5 = "9855b6d802d7fe5b7bd5b196a2271655"

[Zstd]
homepage = "https://facebook.github.io/zstd/"
url = "https://github.com/facebook/zstd/releases/download/v1.5.5/zstd-1.5.5.tar.gz"
md5 = "63251602329a106220e0a5ad26ba656f"
